---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/spicepod: {{ toYaml .Values.spicepod | sha256sum }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spiceai
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          workingDir: /app
          command:
            [
              "/usr/local/bin/spiced",
              "--http",
              "0.0.0.0:8090",
              "--metrics",
              "0.0.0.0:9090",
              "--flight",
              "0.0.0.0:50090",
              "--open_telemetry",
              "0.0.0.0:50052"
            ]
          env:
            {{- if .Values.additionalEnv }}
            {{- .Values.additionalEnv | toYaml | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8090
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 50090
              name: flight
            - containerPort: 50052
              name: otel
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
          readinessProbe:
            httpGet:
              path: /v1/ready
              port: 8090
          startupProbe:
            httpGet:
              path: /health
              port: 8090
          volumeMounts:
            {{- if .Values.volumeMounts }}
            {{- .Values.volumeMounts | toYaml | nindent 12 }}
            {{- end }}
            - name: spiceai-config-volume
              mountPath: /app/spicepod.yaml
              subPath: spicepod.yaml
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.volumes }}
        {{- .Values.volumes | toYaml | nindent 8 }}
        {{- end }}
        - name: spiceai-config-volume
          configMap:
            name: {{ .Release.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: 8090
      name: http
    - port: 9090
      name: metrics
    - port: 50090
      name: flight
    - port: 50052
      name: otel
  selector:
    app: {{ .Release.Name }}
