---
name: lint code base

on:
  pull_request:
    branches:
      - trunk
      - release-*

jobs:
  golangci:
    name: lint golang code
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: Build and copy dashboard
        working-directory: dashboard
        run: make

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=2m

  pylint:
    name: lint python code (syntax)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requirements
        working-directory: ai/src
        run: |
          python -m pip install -r requirements/production.txt
      - name: Install pylint
        working-directory: ai/src
        run: |
          pip install pylint
      - name: Analysing the AI code with pylint
        working-directory: ai/src
        run: |
          find -name '*.py' -not -path './proto/*' -and -not -path './venv/*' | xargs pylint

  flake8:
    name: lint python code (PEP8 + flake)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install flake8
        working-directory: ai/src
        run: |
          pip install flake8
      - name: Analysing the AI code with flake8
        working-directory: ai/src
        run: |
          find -name '*.py' -not -path './proto/*' -and -not -path './venv/*' | xargs flake8
