name: spice-mysql-bench docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Pull MySQL Docker image
      run: docker pull mysql:latest

    - name: Start temporary MySQL server
      run: |
        docker run --name spice-mysql-bench-temp -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql:latest --local-infile=1
        sleep 10

    - name: Install necessary tools
      run: sudo apt-get update && sudo apt-get install -y git make gcc

    - name: Initialize TPCH data
      working-directory: ./test/tpch
      run: |
        make tpch-init
        for sf in 0.01 1; do
          DB_NAME=tpch_sf${sf//./_}
          DBGEN_SCALE=$sf make tpch-gen
          DB_HOST=127.0.0.1 DB_PORT=3306 DB_USER=root DB_PASS=root DB_NAME=$DB_NAME ADD_INDEXES=true make mysql-init
          DB_HOST=127.0.0.1 DB_PORT=3306 DB_USER=root DB_PASS=root DB_NAME=$DB_NAME make mysql-load
          echo "CREATE DATABASE IF NOT EXISTS $DB_NAME;" >mysql-bench/backup_$DB_NAME.sql
          echo "USE $DB_NAME;" >> mysql-bench/backup_$DB_NAME.sql
          docker exec spice-mysql-bench-temp sh -c "exec mysqldump -u root -proot ${DB_NAME}" >> mysql-bench/backup_$DB_NAME.sql
        done

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./test/tpch/mysql-bench
        file: ./test/tpch/mysql-bench/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/spiceai/spice-mysql-bench:latest
          ghcr.io/spiceai/spice-mysql-bench:${{ github.sha }}